name: flutter_application_1
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  image_picker: ^0.8.3+2
  url_launcher: ^6.0.9
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.5
  firebase_storage: ^12.3.4
  permission_handler: ^11.3.1
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.2.4

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets: 
  - assets/ventelabarabai.png
  - assets/backTo70s.png
  - assets/highnatural.png
  - assets/lownatural.png